services:
  messengermvc2:
    image: ${DOCKER_REGISTRY-}messengermvc2
    build:
      context: .
      dockerfile: MessengerMVC2/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mynetwork
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "MessengerMVC2Db"
      POSTGRES_USER: "shamil"
      POSTGRES_PASSWORD: "shamil1998"
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shamil"]
      interval: 10s
      timeout: 5s
      retries: 5
    
volumes:
  pg_data:

networks:
  mynetwork: